version: '3.8'
services:
  service-web:
    build: .
    image: nusncl1/service-web
    container_name: service-web
    ports:
      - "8999:8999"
    volumes:
      - ~/application.properties:/application.properties
