version: '3.3'
services:
  service-web:
    image: nusncl1/service-web:latest
    container_name: service-web
    command: java -jar web-service.jar
    ports:
      - "80:8999"
    volumes:
      - ~/application.properties:/application.properties
      